/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButtonComponent {
        "bgColor": 'red' | 'black' | 'white';
        "icon": string;
        "text": string;
        "textColor": 'red' | 'black' | 'white';
    }
}
export interface MyButtonComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyButtonComponentElement;
}
declare global {
    interface HTMLMyButtonComponentElement extends Components.MyButtonComponent, HTMLStencilElement {
    }
    var HTMLMyButtonComponentElement: {
        prototype: HTMLMyButtonComponentElement;
        new (): HTMLMyButtonComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-button-component": HTMLMyButtonComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyButtonComponent {
        "bgColor"?: 'red' | 'black' | 'white';
        "icon"?: string;
        "onBtnClicked"?: (event: MyButtonComponentCustomEvent<any>) => void;
        "text"?: string;
        "textColor"?: 'red' | 'black' | 'white';
    }
    interface IntrinsicElements {
        "my-button-component": MyButtonComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button-component": LocalJSX.MyButtonComponent & JSXBase.HTMLAttributes<HTMLMyButtonComponentElement>;
        }
    }
}
